app:
  name: "sprout_server"
  mode: "dev"
  port: 8081
  default_avatar: "./static/images/avatar.jpg"
  salt_prefix: "abcdefghijklmnnmlkjihg"
  version: "v0.1.1"

log:
  level: "debug"
  filename: "sprout_server.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "root1234"
  dbname: "sql_demo"

redis:
  host: "127.0.0.1"
  port: 6379
  password: "redis1234"
  db: 0
  pool_size: 100
smtp:
  host: "smtp.xxx.com"
  port: "25"
  password: "abcdefg"
  user: "abc@xxx.com"
  userName: "admin <abc@xxx.com>"
