app:
  name: "sprout_server"
  mode: "dev"
  port: 8081
  version: "v0.1.1"

log:
  level: "debug"
  filename: "sprout_server.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "root1234"
  abname: "sql_demo"

redis:
  host: "127.0.0.1"
  port: 6379
  password: "redis1234"
  db: 0
  pool_size: 100
