version: "3.3"

services:
  sprout_server:
    container_name: sprout_server
    ports:
      - 8081:8081
    build:
      context: ./
      dockerfile: Dockerfile
networks:
  default:
    external:
      name: mybridge